### ISSUE TITLE
Scandir error

### ISSUE THREAD

**Issue by fakesmile723** [AkAbhijit/Hydra#4]
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\raoes\Downloads\Hydra-main\Hydra-main\Src\Commands\Slash'
    at readdirSync (node:fs:1390:3)
    at module.exports (C:\Users\raoes\Downloads\Hydra-main\Hydra-main\Src\Scripts\Slash.js:12:5)
    at C:\Users\raoes\Downloads\Hydra-main\Hydra-main\Src\Base\Client.js:134:101
    at Array.forEach (<anonymous>)
    at Savaan.connect (C:\Users\raoes\Downloads\Hydra-main\Hydra-main\Src\Base\Client.js:134:50)
    at new Savaan (C:\Users\raoes\Downloads\Hydra-main\Hydra-main\Src\Base\Client.js:57:14)
    at Object.<anonymous> (C:\Users\raoes\Downloads\Hydra-main\Hydra-main\Src\Saavan.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\raoes\\Downloads\\Hydra-main\\Hydra-main\\Src\\Commands\\Slash'

**Comment by AkAbhijit** [comment]
Fixed
